### ISSUE TITLE
Unescape quoted strings in actions and assertions

### ISSUE THREAD

**Issue by webignition** [webignition/php-basil-parser#108]
Need to be able to support:

```yaml
actions:
  - click ".button"

assertions:
  - \".heading\" contains "Hello World"

```
